Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<LifespanOn.main() running at /home/heynemann/src/fastapi-dishka/.venv/lib/python3.13/site-packages/uvicorn/lifespan/on.py:86> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<LifespanOn.main() running at /home/heynemann/src/fastapi-dishka/.venv/lib/python3.13/site-packages/uvicorn/lifespan/on.py:86> wait_for=<Future pending cb=[Task.task_wakeup()]>>
ERROR:    Traceback (most recent call last):
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/queues.py", line 186, in get
    await getter
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heynemann/src/fastapi-dishka/.venv/lib/python3.13/site-packages/starlette/routing.py", line 699, in lifespan
    await receive()
  File "/home/heynemann/src/fastapi-dishka/.venv/lib/python3.13/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/queues.py", line 188, in get
    getter.cancel()  # Just in case getter is not done yet.
    ~~~~~~~~~~~~~^^
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

ERROR:    Traceback (most recent call last):
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/queues.py", line 186, in get
    await getter
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/heynemann/src/fastapi-dishka/.venv/lib/python3.13/site-packages/starlette/routing.py", line 699, in lifespan
    await receive()
  File "/home/heynemann/src/fastapi-dishka/.venv/lib/python3.13/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/queues.py", line 188, in get
    getter.cancel()  # Just in case getter is not done yet.
    ~~~~~~~~~~~~~^^
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/base_events.py", line 833, in call_soon
    self._check_closed()
    ~~~~~~~~~~~~~~~~~~^^
  File "/home/heynemann/.pyenv/versions/3.13.4/lib/python3.13/asyncio/base_events.py", line 556, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

